//! IBE Golden Vector Fixtures (Auto-generated by Rust test generator)
//! Run: cargo test --package aptos-dkg generate_golden_vectors -- --ignored --nocapture

module ibe_golden_vector_fixtures {
    use std::vector;

    // ====================================
    // Identity Fixtures
    // ====================================

    public fun identity_0_1000000000000(): vector<u8> {
        x"cd2f0ecdda375c87027bcbd9a8b429057062065239267bfd2496e844b81f7355"
    }

    // ====================================
    // Roundtrip 1: 5 validators, threshold 3, equal weights (PVSS-based)
    // ====================================

    public fun roundtrip_1_identity(): vector<u8> { x"e3fb053eedce65f62fcbbfd56fe9bbec0abe3bfcc3c5ec54a913bd50c51a5dfe" }
    public fun roundtrip_1_threshold(): u64 { 3 }
    public fun roundtrip_1_total_weight(): u64 { 5 }
    public fun roundtrip_1_validator_indices(): vector<u64> { vector[0, 1, 2, 3, 4] }
    public fun roundtrip_1_validator_weights(): vector<u64> { vector[1, 1, 1, 1, 1] }

    public fun roundtrip_1_dk_shares(): vector<vector<vector<u8>>> {
        vector[
            vector[x"9722f3fe074ff0467af66bbb6564aaeec41ac369dbc55a520e1197e2cabd01489fac2b5260c049e9ed26fdd872391d2d"],
            vector[x"b0cc6092fc45df1b1318952c08dd2a877b5b19deb725b63cfc41c48e84da6e8f77600efe4d38aac33273a87775112a31"],
            vector[x"ac20a63c6b62ed15a3424d85af25eb006795eba2172996529afbb70d29d1a57066a37ee1c98dea843fa2c998cb6b3919"],
            vector[x"b42700b02c7997b35f244481afa657a601e915046aed0dee5dcde214e91efdecbf3fcc9d21c11907aac23a84c43927d2"],
            vector[x"891c64345686bd154a277a7540ed7c32ad7a0abe30a40586515bf07738e6f63f054b6a55d6d5a2288da37f15335618bf"]
        }
    }

    public fun roundtrip_1_reconstructed_dk(): vector<u8> { x"a46066de7604d2d51825cd139d720523d5584654cda567f80c3779304d2dec8842b41a7feec0db2a202409f45492593c" }

    // ====================================
    // Roundtrip 2: 4 validators, threshold 2, equal weights
    // ====================================

    public fun roundtrip_2_identity(): vector<u8> { x"fe35f39be89aa3d57c43d37f0a4ecb02908c7a82c877eaf5c6517224aa09c46c" }
    public fun roundtrip_2_threshold(): u64 { 2 }
    public fun roundtrip_2_total_weight(): u64 { 4 }
    public fun roundtrip_2_validator_indices(): vector<u64> { vector[0, 1, 2, 3] }
    public fun roundtrip_2_validator_weights(): vector<u64> { vector[1, 1, 1, 1] }

    public fun roundtrip_2_dk_shares(): vector<vector<vector<u8>>> {
        vector[
            vector[x"b60d3ddf9b0a596918276b9016723540aab31e024153a3f5b214150022e34444c2a8c6a08f2bc68f289f715ffdb93192"],
            vector[x"864b4a9211b0eb77dab0df356f124a86f946ed9004de11e0c0ae1ac529301eef9adf443373f9ab0a33d393db38528337"],
            vector[x"8f6e359c3d6d94ba5420695da8b441f1268d0bbe616bad8820125730a60eb589ddbf94e33c425e0a7871ec3d1a2ef520"],
            vector[x"a6edf2ef32d2e25a10b1374dd1c758545036f743f556252ae3451a489d454414820e4d9e287965a2c4a318e3d409c6c0"]
        }
    }

    public fun roundtrip_2_reconstructed_dk(): vector<u8> { x"9266dbe7f2c3a699fa1767d30c56507f792ee751fe457c6958f04dd8e0b6333d71fa609664b2cfada489547761effeb1" }

    // ====================================
    // Roundtrip 3: 3 validators, threshold 3, unequal weights [2,1,2]
    // ====================================

    public fun roundtrip_3_identity(): vector<u8> { x"de8e8b23a9e541393a1835326e2e07e51571d61dd42a0c9dd1c2dab16186986d" }
    public fun roundtrip_3_threshold(): u64 { 3 }
    public fun roundtrip_3_total_weight(): u64 { 5 }
    public fun roundtrip_3_validator_indices(): vector<u64> { vector[0, 1, 2] }
    public fun roundtrip_3_validator_weights(): vector<u64> { vector[2, 1, 2] }

    public fun roundtrip_3_dk_shares(): vector<vector<vector<u8>>> {
        vector[
            vector[x"8723f166aabb441baeb0df1eddfd332c3f5ec3a0b41ae92c54aee283021deb98ac79248dbabd5244bde583b553a4222b", x"aff1dc2c26fcb7f48a61f27e34933e8818c3e8f3905ee9cda4956b89d343bc751ed39be795a7762a5aefe742ef192836"],
            vector[x"8a96fb8faed4eedb44496140cf2a47c09a56eca0da3a61e8306d11554ca90ba06493ec1d4523cf39326451dbb67d4549"],
            vector[x"aff15e922d0418a29c420f384db7524fdf52bfdb16b34710c07b38a40167711c660af07d6261a031a264b78acc63214f", x"a24237a89cf507e05553e93950cac155d24496c8d7b5568d4443223826916141c1517ff43873b0fec0a03613f90bec0a"]
        }
    }

    public fun roundtrip_3_reconstructed_dk(): vector<u8> { x"afbaa0adb5ab4ef5d1c72e1aab6497f1fabd61d8f24a7c642593978e4ff18a080c10228fa8a61a8ec9f5ad0e15de1a76" }

    // ====================================
    // Roundtrip 4: 4 validators, threshold 3, unequal weights [2,3,2,1]
    // ====================================

    public fun roundtrip_4_identity(): vector<u8> { x"5758871061dc3844df56aa064d31f0bc171b005ea70e9b1f866d17308e7db2a1" }
    public fun roundtrip_4_threshold(): u64 { 3 }
    public fun roundtrip_4_total_weight(): u64 { 8 }
    public fun roundtrip_4_validator_indices(): vector<u64> { vector[0, 1, 2, 3] }
    public fun roundtrip_4_validator_weights(): vector<u64> { vector[2, 3, 2, 1] }

    public fun roundtrip_4_dk_shares(): vector<vector<vector<u8>>> {
        vector[
            vector[x"89034bbd72ce9be382e9441f2a44b9c362fa0300fcc4e800ca3a9f6f9d74700dfce3909f28f56ae073722c1c6725c2b8", x"b407665ba45951d24b1f77e2ac8ca13c73a61f3a84a7151021c7bd21bc40c2afb1d107aa91cb33b4d60d4de96aec93d3"],
            vector[x"9250c34552b6fc46dc9f0ebb3e74c513b8bee8263cb51375b880c1c011841dc0f06f036dacd8ce1ec9255910d0c89c59", x"a278603fcd8b53580bf6e5f220399cf3babb8e4dae4722c1f16863728488cdf5ee8d003b00d1cba54647d33733434ab2", x"899cb3ae08d459005e7c0dd1a89ffff1ef27c8b5c0a71d5f8c6cac56a5ceeb40934b652147cd16ed8c4e520a80dd7d92"],
            vector[x"af0cda59649a9ca324c33ae5d903bc5487c49678a88c19be4eaea73e4bcb0c497275427955c47b0c3d31cca83ce60eeb", x"af1ced40168c252b4937229e8e28ecd61ab4aacfaf2b1790aa65368f4b96f1d799739ec8471f98767617bd658f80d260"],
            vector[x"b3119a32f5b4d0ac7fa283e13cb7e09e971778d889b02e281e74d5b56b2eb73f6a0ca0d30549717bad57f3e8102b1079"]
        }
    }

    public fun roundtrip_4_reconstructed_dk(): vector<u8> { x"af3b251c96136842613b45d09a222986330395b5699449526fca7405e8d6bb2743306b193cf10bfdbcfe8cdc468eaa8d" }

    // ================================
    // Helper Functions
    // ================================

    public fun get_roundtrip_dk_shares(index: u64): vector<vector<vector<u8>>> {
        if (index == 1) roundtrip_1_dk_shares()
        else if (index == 2) roundtrip_2_dk_shares()
        else if (index == 3) roundtrip_3_dk_shares()
        else if (index == 4) roundtrip_4_dk_shares()
        else vector::empty()
    }

}
