//! IBE (Identity-Based Encryption) tests for timelock
//!
//! These tests verify that IBE encryption/decryption works correctly
//! using the keys generated by DKG and published by the timelock system.

use super::test_helpers::{create_timelock_swarm, TimelockTestConfig};
use aptos_dkg::ibe::{compute_timelock_identity, ibe_decrypt, ibe_encrypt};
use aptos_dkg::pvss::traits::Transcript;
use aptos_logger::info;
use aptos_types::dkg::real_dkg::Transcripts;
use blstrs::G1Projective;
use group::Group;
use std::time::Duration;
use tokio::time::sleep;

/// Test that we can extract the IBE public key from the DKG transcript.
#[tokio::test]
async fn test_ibe_extract_public_key_from_transcript() {
    let config = TimelockTestConfig {
        timelock_interval_secs: Some(5),
        ..Default::default()
    };
    let (_swarm, client, _chain_id) = create_timelock_swarm(config).await;

    let initial_interval = super::get_current_interval(&client).await.unwrap();
    let target_interval = initial_interval + 1;

    info!("Waiting for rotation to interval {}", target_interval);
    super::wait_for_interval_rotation(&client, target_interval, 30)
        .await
        .unwrap();

    info!("Fetching DKG transcript for interval {}", target_interval);
    let mut transcript_bytes = Vec::new();
    for _ in 0..60 {
        if let Ok(bytes) = super::verify_public_key_published(&client, target_interval).await {
            transcript_bytes = bytes;
            break;
        }
        sleep(Duration::from_secs(1)).await;
    }
    assert!(!transcript_bytes.is_empty(), "Failed to get transcript");

    info!("Deserializing transcript");
    let transcripts: Transcripts =
        bcs::from_bytes(&transcript_bytes).expect("Failed to deserialize transcripts");

    // Main transcript is always present (not Option)
    let main_transcript = &transcripts.main;
    let dealt_pubkey = main_transcript.get_dealt_public_key();
    let mpk_g2 = dealt_pubkey.as_group_element();

    info!("✅ Successfully extracted IBE public key (G2 element)");

    // Verify the public key is valid (non-identity)
    let is_identity: bool = mpk_g2.is_identity().into();
    assert!(
        !is_identity,
        "Public key should not be identity element"
    );
}

/// Test that we can encrypt a message using IBE.
#[tokio::test]
async fn test_ibe_encrypt_message() {
    let config = TimelockTestConfig {
        timelock_interval_secs: Some(5),
        ..Default::default()
    };
    let (_swarm, client, chain_id) = create_timelock_swarm(config).await;

    let initial_interval = super::get_current_interval(&client).await.unwrap();
    let target_interval = initial_interval + 1;

    info!("Waiting for rotation and transcript");
    super::wait_for_interval_rotation(&client, target_interval, 30)
        .await
        .unwrap();

    let mut transcript_bytes = Vec::new();
    for _ in 0..60 {
        if let Ok(bytes) = super::verify_public_key_published(&client, target_interval).await {
            transcript_bytes = bytes;
            break;
        }
        sleep(Duration::from_secs(1)).await;
    }
    assert!(!transcript_bytes.is_empty(), "Failed to get transcript");

    // Extract IBE public key
    let transcripts: Transcripts = bcs::from_bytes(&transcript_bytes).unwrap();
    let main_transcript = &transcripts.main;
    let dealt_pubkey = main_transcript.get_dealt_public_key();
    let mpk_g2 = dealt_pubkey.as_group_element();

    // Create identity for this interval and chain
    let identity = compute_timelock_identity(target_interval, chain_id.id());
    info!(
        "Created identity for chain_id={}, interval={}",
        chain_id.id(),
        target_interval
    );

    // Encrypt a test message
    let plaintext = b"Hello, timelock IBE!";
    info!("Encrypting message: {:?}", std::str::from_utf8(plaintext));

    let ciphertext = ibe_encrypt(&mpk_g2, &identity, plaintext).expect("Encryption failed");

    info!("✅ Successfully encrypted message");
    info!("Ciphertext V component length: {} bytes", ciphertext.v.len());

    // Verify ciphertext is non-trivial
    assert!(
        ciphertext.v.len() >= plaintext.len(),
        "Ciphertext V component should be at least as large as plaintext"
    );
}

/// Test the full IBE encrypt/decrypt flow.
#[tokio::test]
async fn test_ibe_encrypt_decrypt_e2e() {
    let config = TimelockTestConfig {
        timelock_interval_secs: Some(5),
        ..Default::default()
    };
    let (_swarm, client, chain_id) = create_timelock_swarm(config).await;

    let initial_interval = super::get_current_interval(&client).await.unwrap();
    let target_interval = initial_interval + 1;

    info!("Step 1: Waiting for rotation to interval {}", target_interval);
    super::wait_for_interval_rotation(&client, target_interval, 30)
        .await
        .unwrap();

    info!("Step 2: Fetching DKG transcript");
    let mut transcript_bytes = Vec::new();
    for _ in 0..60 {
        if let Ok(bytes) = super::verify_public_key_published(&client, target_interval).await {
            transcript_bytes = bytes;
            break;
        }
        sleep(Duration::from_secs(1)).await;
    }
    assert!(!transcript_bytes.is_empty(), "Failed to get transcript");

    info!("Step 3: Extracting IBE public key");
    let transcripts: Transcripts = bcs::from_bytes(&transcript_bytes).unwrap();
    let main_transcript = &transcripts.main;
    let dealt_pubkey = main_transcript.get_dealt_public_key();
    let mpk_g2 = dealt_pubkey.as_group_element();

    info!("Step 4: Encrypting message");
    let identity = compute_timelock_identity(target_interval, chain_id.id());
    let plaintext = b"Secret bid: $1000";
    let ciphertext = ibe_encrypt(&mpk_g2, &identity, plaintext).expect("Encryption failed");
    info!("Encrypted message: {} bytes", ciphertext.v.len());

    info!("Step 5: Waiting for next rotation to trigger secret reveal");
    let reveal_interval = target_interval + 1;
    super::wait_for_interval_rotation(&client, reveal_interval, 30)
        .await
        .unwrap();

    info!("Step 6: Fetching decryption key");
    let mut dk_bytes = None;
    for _ in 0..60 {
        if let Ok(secret) = super::verify_secret_aggregated(&client, target_interval, 3).await {
            dk_bytes = Some(secret);
            break;
        }
        sleep(Duration::from_secs(1)).await;
    }
    assert!(dk_bytes.is_some(), "Failed to get decryption key");

    info!("Step 7: Deserializing decryption key");
    let dk_g1: G1Projective = bcs::from_bytes(&dk_bytes.unwrap())
        .expect("Failed to deserialize decryption key");

    info!("Step 8: Decrypting message");
    let decrypted = ibe_decrypt(&dk_g1, &ciphertext)
        .expect("Failed to decrypt ciphertext");

    info!("Step 9: Verifying decrypted plaintext");
    assert_eq!(
        decrypted, plaintext,
        "Decrypted plaintext should match original"
    );

    info!(
        "✅ IBE E2E test completed successfully: {:?}",
        std::str::from_utf8(&decrypted).unwrap()
    );
}

/// Test that IBE decryption fails with wrong decryption key.
#[tokio::test]
async fn test_ibe_decrypt_fails_with_wrong_key() {
    let config = TimelockTestConfig {
        timelock_interval_secs: Some(5),
        ..Default::default()
    };
    let (_swarm, client, chain_id) = create_timelock_swarm(config).await;

    let initial_interval = super::get_current_interval(&client).await.unwrap();
    let target_interval = initial_interval + 1;

    info!("Waiting for rotation and encrypting message");
    super::wait_for_interval_rotation(&client, target_interval, 30)
        .await
        .unwrap();

    let mut transcript_bytes = Vec::new();
    for _ in 0..60 {
        if let Ok(bytes) = super::verify_public_key_published(&client, target_interval).await {
            transcript_bytes = bytes;
            break;
        }
        sleep(Duration::from_secs(1)).await;
    }
    assert!(!transcript_bytes.is_empty());

    let transcripts: Transcripts = bcs::from_bytes(&transcript_bytes).unwrap();
    let dealt_pubkey = transcripts.main.get_dealt_public_key();
    let mpk_g2 = dealt_pubkey.as_group_element();

    let identity = compute_timelock_identity(target_interval, chain_id.id());
    let plaintext = b"Secret message";
    let ciphertext = ibe_encrypt(&mpk_g2, &identity, plaintext).expect("Encryption failed");

    // Use a random/wrong decryption key (generator is not the correct DK)
    let wrong_dk = G1Projective::generator();

    info!("Attempting to decrypt with wrong key");
    let result = ibe_decrypt(&wrong_dk, &ciphertext);

    // Decryption should either fail or produce garbage
    if let Ok(decrypted) = result {
        assert_ne!(
            decrypted, plaintext,
            "Decryption with wrong key should not produce correct plaintext"
        );
        info!("✅ Decryption with wrong key produced garbage (as expected)");
    } else {
        info!("✅ Decryption with wrong key failed (as expected)");
    }
}

/// Test that IBE works across multiple intervals.
#[tokio::test]
async fn test_ibe_multiple_intervals() {
    let config = TimelockTestConfig {
        timelock_interval_secs: Some(5),
        ..Default::default()
    };
    let (_swarm, client, chain_id) = create_timelock_swarm(config).await;

    let initial_interval = super::get_current_interval(&client).await.unwrap();

    // Test encryption/decryption for 2 different intervals
    for i in 1..=2 {
        let target_interval = initial_interval + i;
        info!(
            "\n=== Testing IBE for interval {} ===",
            target_interval
        );

        // Wait for rotation
        super::wait_for_interval_rotation(&client, target_interval, 30)
            .await
            .unwrap();

        // Get transcript and encrypt
        let mut transcript_bytes = Vec::new();
        for _ in 0..60 {
            if let Ok(bytes) = super::verify_public_key_published(&client, target_interval).await
            {
                transcript_bytes = bytes;
                break;
            }
            sleep(Duration::from_secs(1)).await;
        }
        assert!(!transcript_bytes.is_empty());

        let transcripts: Transcripts = bcs::from_bytes(&transcript_bytes).unwrap();
        let dealt_pubkey = transcripts.main.get_dealt_public_key();
        let mpk_g2 = dealt_pubkey.as_group_element();

        let identity = compute_timelock_identity(target_interval, chain_id.id());
        let plaintext = format!("Message for interval {}", target_interval);
        let ciphertext =
            ibe_encrypt(&mpk_g2, &identity, plaintext.as_bytes()).expect("Encryption failed");
        info!("Encrypted message for interval {}", target_interval);

        // Wait for reveal
        super::wait_for_interval_rotation(&client, target_interval + 1, 30)
            .await
            .unwrap();

        let mut dk_bytes = None;
        for _ in 0..60 {
            if let Ok(secret) = super::verify_secret_aggregated(&client, target_interval, 3).await
            {
                dk_bytes = Some(secret);
                break;
            }
            sleep(Duration::from_secs(1)).await;
        }
        assert!(dk_bytes.is_some());

        let dk_g1: G1Projective = bcs::from_bytes(&dk_bytes.unwrap()).unwrap();
        let decrypted = ibe_decrypt(&dk_g1, &ciphertext).unwrap();

        assert_eq!(decrypted, plaintext.as_bytes());
        info!("✓ Decrypted successfully for interval {}", target_interval);
    }

    info!("✅ IBE works correctly across multiple intervals");
}
